// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbrkqicfjayxcsfwwyqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdicmtxaWNmamF5eGNzZnd3eXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDU1NDQsImV4cCI6MjA1OTMyMTU0NH0.SHMDwHGafTVEZHEcm9YPTVG80_QShoqkav2zxBzlRjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);